ClinicManagementSystem/Controllers/ClinicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicManagementSystem.Controllers
{
    public class ClinicController : Controller
    {
        HospitalDBEntities db = new HospitalDBEntities();
        // GET: Clinic
        public ActionResult Index()
        {
           TempData["count"] = db.tblClinics.Count();
            return View();
        }
    }
}

ClinicManagementSystem/Controllers/DoctorController.cs
using ClinicManagementSystem.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicManagementSystem.Controllers
{
    public class DoctorController : Controller
    {
        HospitalDBEntities db = new HospitalDBEntities();
        // GET: Doctor
        public ActionResult Index()
        {
            TempData["count"] = db.tblDoctors.Count();
            ViewBag.Role = CommonRepo.Role();
            ViewBag.Clinic = CommonRepo.Clinic();

            return View();
        }
    }
}

ClinicManagementSystem/Controllers/PatientController.cs
using ClinicManagementSystem.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicManagementSystem.Controllers
{
    public class PatientController : Controller
    { HospitalDBEntities db = new HospitalDBEntities();
       
        // GET: Patient
        public ActionResult Index()
        {
            ViewBag.blood = CommonRepo.Blood();
            TempData["count"] = db.tblPatients.Count();
            return View();
        }
    }
}

ClinicManagementSystem/Controllers/StaffController.cs
using ClinicManagementSystem.Api;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClinicManagementSystem.Controllers
{
    public class StaffController : Controller
    {
        HospitalDBEntities db = new HospitalDBEntities();
        // GET: Staff
        public ActionResult Index()
        {
            ViewBag.role = CommonRepo.Role();
            TempData["count"] = db.tblStaffs.Count();


            return View();
        }
    }
}

ClinicManagementSystem/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <script src="~/JS/FontAwesome.min.js"></script>
    <script src="https://kit.fontawesome.com/6c13a248fc.js" crossorigin="anonymous"></script>
    <script src="https://smtpjs.com/v3/smtp.js">
    </script>
    <link href="~/CSS/bootstrap.min.css" rel="stylesheet" />
    <script src="~/JS/bootstrap.bundle.min.js"></script>
    <script src="~/JS/jquery.min.js"></script>

    <style>
        * {
            font-family: 'Montserrat', sans-serif;
            /*font-family: 'Poppins', sans-serif;*/
        }

        .mainDiv {
            height: 100vh;
            display: flex;
            overflow: hidden;
        }

        .leftMenu {
            width: 17%;
            overflow-y: scroll;
        }

        .rightMenu {
            width: 83%;
        }

        .leftMenuDiv h6 {
            margin: 0;
        }

        .leftMenuDiv a:link, a:visited {
            color: #000;
            padding: 13px 0 13px 20px;
            text-decoration: none;
            display: inline-block;
            width: 100%;
            margin-bottom: 8px;
            display: flex;
            align-items: center;
        }

        .leftMenuDiv h6 .active {
            background: #00acb1;
            color: #fff;
        }

        .leftMenuDiv h6 i {
            margin-right: 10px;
            font-size: 20px;
        }

        ::-webkit-scrollbar {
            width: 0px;
        }

        ::-webkit-scrollbar-thumb {
            background: #d5d5d5;
            border-radius: 10px;
        }

        .modal-body input {
            margin-bottom: 8px;
        }
    </style>
</head>
<body>
    <div class="mainDiv">
        <div class="leftMenu border-end p-0">
            <div class="sticky-top bg-white">
                <a href="#">
                    <img src="~/Images/logo.png" alt="Alternate Text" class="w-75 m-3 " />
                </a>
            </div>

            <div class="leftMenuDiv mt-2">
                <h6><a href="@Url.Action("Index", "Home")" class="active"><i class="fa-solid fa-gauge"></i> Dashboard</a></h6>
                <h6><a href="@Url.Action("Index", "Clinic")"><i class="fa-solid fa-hospital"></i> Clinic</a></h6>
                <h6><a href="@Url.Action("Index", "Doctor")"><i class="fa-solid fa-stethoscope"></i> Doctor</a></h6>
                <h6><a href="@Url.Action("Index", "Staff")"><i class="fa-solid fa-user-nurse"></i> Staff</a></h6>
                <h6><a href="@Url.Action("Index", "Patient")"><i class="fa-solid fa-bed"></i> Patient</a></h6>
                <h6><a href="@Url.Action("Index", "CasePaper")"><i class="fa-solid fa-clipboard-list"></i> Casepaper</a></h6>
                <h6><a href="@Url.Action("Index", "Appointment")"><i class="fa-solid fa-calendar-check"></i> Appointment</a></h6>
                <h6><a href="@Url.Action("Index", "Medicines")"><i class="fa-solid fa-pills"></i> Medicines</a></h6>
                <h6><a href="@Url.Action("Index", "Prescription")"><i class="fa-solid fa-pills"></i> Prescription</a></h6>
            </div>
        </div>
        <div class="rightMenu">
            <div class="row m-0 p-2 bg-white">
                <div class="col-md-11"></div>
                <div class="col-md-1 text-center">
                    <div class="dropdown">
                        <img src="~/Images/male-doctor.png" alt="Alternate Text" class="rounded-pill dropdown-toggle border" style="width:65%" type="button" data-bs-toggle="dropdown" aria-expanded="false" />
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
    <script src="~/JS/jquery.validate.min.js"></script>
    <script src="~/JS/jquery.validate.unobtrusive.min.js"></script>
</body>

</html>

ClinicManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <script src="~/JS/jquery.min.js"></script>
    <script src="~/JS/boxicons.js"></script>
    <link href="~/CSS/bootstrap.min.css" rel="stylesheet" />
    <script src="~/JS/bootstrap.bundle.min.js"></script>
    <link href="~/CSS/boxicons.min.css" rel="stylesheet" />
   
</head>
<body>
    <div class="body-content">
        @RenderBody()
    </div>

    <script src="~/JS/jquery.validate.min.js"></script>
    <script src="~/JS/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>